version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx01
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    volumes:
      - ./src:/src
      - ./nginx_config:/etc/nginx/conf.d
    depends_on:
      - django
  django:
    build: .
    container_name: django01
    volumes:
      - ./src:/src
      - ./nginx_config:/nginx_config
    expose:
      - "${LISTEN_PORT}"
  broker-redis:
    image: redis:latest
    container_name: broker-redis01
    ports:
     - "${BROKER_PORT}:${BROKER_PORT}"
  db-postgres:
    image: postgres:latest
    container_name: db-postgres01

