version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx01
    ports:
      - "7777:7777"
    volumes:
      - ./src:/src
      - ./nginx_config:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    build: .
    container_name: web01
    volumes:
      - ./src:/src
      - ./nginx_config:/nginx_config
    expose:
      - "7777"
#    links:
#      - redis
#  redis:
#    image: redis:latest
#    container_name: redis01
#    ports:
#     - '6379:6379'
