version: '3'  
services:  
  nginx:
    image: nginx:latest
    container_name: nginx01
    restart: always
    ports:
      - "${LISTEN_PORT}:${LISTEN_PORT}"
    depends_on:
      - django
    networks:
      - django
    volumes:
      - ./src:/src
      - ./nginx_config:/etc/nginx/conf.d
  django:
    build: .
    container_name: django01
    restart: always
    networks:
      - django
    volumes:
      - ./src:/src
      - ./run:/run
      - ./nginx_config:/nginx_config
      - ./env:/env
    expose:
      - "${LISTEN_PORT}"
  broker-redis:
    image: redis:latest
    container_name: broker-redis01
    restart: always
    ports:
     - "${BROKER_PORT}:${BROKER_PORT}"
    networks:
      - django
  db-postgres:
    image: postgres:latest
    container_name: db-postgres01
    restart: always
    volumes:
      - ./database-postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_DB: "${DB_NAME}"
#    ports:
#      - "${DB_PORT}:${DB_PORT}"
    networks:
      django:
        aliases:
          - "${DB_HOST}"
  db-mysql:
    image: mysql:latest
    container_name: db-mysql01
    entrypoint: ['docker-entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    restart: always
    volumes:
      - ./database-mysql:/var/lib/mysql
    environment:
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_USER: "${DB_USER}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
#    ports:
#      - "${DB_PORT}:${DB_PORT}"
    networks:
      django:
        aliases:
          - "${DB_HOST}"

networks:
  django:
    driver: bridge
